version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      BOT_TOKEN: ${BOT_TOKEN}
      SSL: ${SSL}

  celery:
    build: .
    command: celery -A yondosh_core worker --loglevel=info
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      BOT_TOKEN: ${BOT_TOKEN}
      SSL: ${SSL}

  celery-beat:
    build: .
    command: celery -A yondosh_core beat --loglevel=info
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      BOT_TOKEN: ${BOT_TOKEN}
      SSL: ${SSL}